const typePost = {
  GET_LIST_MY_POST: 'GET_LIST_MY_POST',
  GET_LIST_USER_POST: 'GET_LIST_USER_POST',
  GET_LIST_USER_POST_SUCCESS: 'GET_LIST_USER_POST_SUCCESS',
  DELETE_LIST_USER_POST: 'DELETE_LIST_USER_POST',
  DELETE_LIST_USER_POST_SUCCESS: 'DELETE_LIST_USER_POST_SUCCESS',

  GET_DETAIL_POST: 'GET_DETAIL_POST',
  GET_DETAIL_POST_SUCCESS: 'GET_DETAIL_POST_SUCCESS',
  GET_LIST_COMMENT: 'GET_LIST_COMMENT',
  GET_LIST_COMMENT_SUCCESS: 'GET_LIST_COMMENT_SUCCESS',

  GET_DATA_REPLY: 'GET_DATA_REPLY',
  GET_DATA_REPLY_SUCCESS: 'GET_DATA_REPLY_SUCCESS',

  ADD_COMMENT_TO_LIST: 'ADD_COMMENT_TO_LIST',
  ADD_REPLY_COMMENT_TO_LIST: 'ADD_REPLY_COMMENT_TO_LIST',
  CHANGE_STATUS_LIKE: 'CHANGE_STATUS_LIKE',

  //SOCKET
  UPDATE_COMMENT_POST_SOCKET: 'UPDATE_COMMENT_POST_SOCKET',
  UPDATE_COMMENT_POST_SOCKET_SUCCESS: 'UPDATE_COMMENT_POST_SOCKET_SUCCESS',
  UPDATE_REPLY_COMMENT_SOCKET: 'UPDATE_REPY_COMMENT_SOCKET',
  UPDATE_REPLY_COMMENT_SOCKET_SUCCESS: 'UPDATE_REPLY_COMMENT_SOCKET_SUCCESS',
  UPDATE_LIKE_POST_SOCKET: 'UPDATE_LIKE_POST_SOCKET',
  UPDATE_LIKE_COMMENT_SOCKET: 'UPDATE_LIKE_COMMENT_SOCKET',
  UPDATE_LIKE_COMMENT_SOCKET_SUCCESS: 'UPDATE_LIKE_COMMENT_SOCKET_SUCCESS',
  UPDATE_LIKE_REPLY_COMMENT_SOCKET: 'UPDATE_LIKE_REPLY_COMMENT_SOCKET',
  UPDATE_LIKE_REPLY_COMMENT_SOCKET_SUCCESS:
    'UPDATE_LIKE_REPLY_COMMENT_SOCKET_SUCCESS',
  CLEAR_DATA_DETAIL_POST: 'CLEAR_DATA_DETAIL_POST',
  LOADING_FINISH: 'LOADING_FINISH',
  LOADING_START: 'LOADING_START',
};

export {typePost};
