const typeChatGPT = {
  GET_LIST_MESSAGE_CHAT_GPT: 'GET_LIST_MESSAGE_CHAT_GPT',
  GET_LIST_MESSAGE_CHAT_GPT_SUCCESS: 'GET_LIST_MESSAGE_CHAT_GPT_SUCCESS',
  ADD_MESSAGE_TO_LIST: 'ADD_MESSAGE_TO_LIST',
};

export {typeChatGPT};
