const typeChatGPT = {
  GET_LIST_MESSAGE_CHAT_GPT: 'GET_LIST_MESSAGE_CHAT_GPT',
  GET_LIST_MESSAGE_CHAT_GPT_SUCCESS: 'GET_LIST_MESSAGE_CHAT_GPT_SUCCESS',
  ADD_MESSAGE_TO_LIST: 'ADD_MESSAGE_TO_LIST',
  SAVE_SUGGEST_MESSAGE_ID: 'SAVE_SUGEST_MESSGAE_ID',
  SAVE_IS_POST_SUGGEST_MESSAGE: 'SAVE_IS_POST_SUGGEST_MESSAGE',
};

export {typeChatGPT};
