const typeForum = {
  CHANGE_TAB_FORUM: 'CHANGE_TAB_FORUM',
  GET_FORUM_BY_TAB: 'GET_FORUM_BY_TAB',
  GET_FORUM_BY_TAB_SUCCESS: 'GET_FORUM_BY_TAB_SUCCESS',
  GET_LIST_TAB_FORUM: 'GET_LIST_TAB_FORUM',
  GET_LIST_TAB_FORUM_SUCCESS: 'GET_LIST_TAB_FORUM_SUCCESS',
  CLEAR_FORUM: 'CLEAR_FORUM',
  LOADING_FORUM_DONE: 'LOADING_FORUM_DONE',
  LIKE_POST_FORUM: 'LIKE_POST_FORUM',
  FETCH_DATA_REQUEST: 'FETCH_DATA_REQUEST',
  DELETE_POST_FORUM: 'DELETE_POST_FORUM',
  LOADING_LIST_FORUM: 'LOADING_LIST_FORUM',
};

export {typeForum};
