const typeChat = {
  GET_LIST_MESSAGE_CHAT: 'GET_LIST_MESSAGE_CHAT',
  GET_LIST_MESSAGE_CHAT_SUCCESS: 'GET_LIST_MESSAGE_CHAT_SUCCESS',
  ADD_MESSAGE_TO_LIST: 'ADD_MESSAGE_TO_LIST',
  GET_DETAIL_MESSAGE: 'GET_DETAIL_MESSAGE',
  SAVE_TOPIC_ID: 'SAVE_TOPIC_ID',
  CLEAR_DATA_CHAT: 'CLEAR_DATA_CHAT',
  CHANGE_STATUS_MUTE: 'CHANGE_STATUS_MUTE',
};

export {typeChat};
