const typeExplore = {
  CHANGE_PAGE_EXPLORE: 'CHANGE_PAGE_EXPLORE',
  GET_DATA_ARTICLE_SUCCESS: 'GET_DATA_ARTICLE_SUCCESS',
  GET_DATA_PODCAST_SUCCESS: 'GET_DATA_PODCAST_SUCCESS',
  GET_DATA_VIDEO_SUCCESS: 'GET_DATA_VIDEO_SUCCESS',
  CHANGE_OPTION: 'CHANGE_OPTION',
  CHANGE_FILTER: 'CHANGE_FILTER',
  CHANGE_EXPERT: 'CHANGE_EXPERT',
  CLEAR_EXPLORE: 'CLEAR_EXPLORE',
  LOADING_ARTICLE_DONE: 'LOADING_ARTICLE_DONE',
  LOADING_PODCAST_DONE: 'LOADING_PODCAST_DONE',
  LOADING_VIDEO_DONE: 'LOADING_VIDEO_DONE',
  CHANGE_FILTER_EXPLORE: 'CHANGE_FILTER_EXPLORE',
  LIKE_PODCAST_EXPLORE: 'LIKE_PODCAST_EXPLORE',
  PAY_ARTICLE_EXPLORE: 'PAY_ARTICLE_EXPLORE',
  PAY_PODCAST_EXPLORE: 'PAY_PODCAST_EXPLORE',
  PAY_VIDEO_EXPLORE: 'PAY_VIDEO_EXPLORE',
  FETCH_DATA_REQUEST: 'FETCH_DATA_REQUEST',
};

export {typeExplore};
