export const event = {
  TAB: {
    CLICK_TAB_HOME: 'CLICK_TAB_HOME',
    CLICK_TAB_EXPLORE: 'CLICK_TAB_EXPLORE',
    CLICK_TAB_COMMUNITY: 'CLICK_TAB_COMMUNITY',
    CLICK_TAB_LIVE_TALKS: 'CLICK_TAB_LIVE_TALKS',
  },
  AUTH: {
    CLICK_SIGN_UP: 'af_signup',
    CLICK_SIGN_UP_SUCCESS: 'af_complete_registration',
    CLICK_LOGIN: 'af_login',
  },
  LIVE_ROOM: {
    CLICK_CREATE_NEW_ROOM: 'af_click_create_room',
    CLICK_CREATE_NEW_ROOM_SUCCESS: 'af_click_complete_create_room',
  },
  EXPLORE: {
    CLICK_EXPLORE: 'af_click_filter',
  },
  SCREEN: {
    INTRO: 'af_screen_intro',
    LOGIN: 'af_screen_login',
    SIGN_UP: 'af_screen_signUp',
    CHANGE_LANGUAGE: 'af_screen_change_language',
    CHOOSE_DUE_DATE: 'af_screen_choose_due_date',
    CALCULATE_DUE_DATE: 'af_screen_calculate_due_date',
    RESULT_DUE_DATE: 'af_screen_result_due_date',

    PROFILE_SETTINGS: 'af_screen_profile_setting',
    HOME: 'af_screen_home',
    WEEKLY_ARTICLES: 'af_screen_weekly_articles',
    DETAIL_ARTICLE: 'af_screen_detail_articles',
    SIZE_COMPARISON: 'af_screen_size_comparison',
    DAILY_READS: 'af_screen_daily_reads',
    VIDEO_LIST: 'af_screen_video_list',
    TIME_LINE: 'af_screen_important_dates_of_your_pregnancy',
    NEW_FEED: 'af_screen_list_post',
    DETAIL_NEWFEED: 'af_screen_detail_post',
    DETAIL_VIDEO: 'af_screen_detail_video',
    MY_NEWFEED: 'af_screen_my_post',
    SETTING_SCREEN: 'af_screen_setting_screen',
    CREATE_NEWPOST: 'af_screen_create_post',
    LIST_PODCAST: 'af_screen_list_podcast',
    DETAIL_PODCAST: 'af_screen_detail_podcast',
    EDIT_POST: 'af_screen_edit_post',
    LIST_BLOCKED_USER: 'af_screen_list_blocked_user',
    DETAIL_USER: 'af_screen_detail_user',
    CHAT_GPT: 'af_screen_chatGPT',
    NOTIFICATION_LIST: 'af_screen_notification_list',
    SAVED_ARTICLES: 'af_screen_saved_articles',
    MY_NEWFEED_SETTING: 'af_screen_my_newfeed_setting',
    PRIVACY_POLICY: 'af_screen_privacy_policy',
    LIST_MESSAGE: 'af_screen_list_message',
    DETAIL_CHAT: 'af_screen_detail_chat',
    CALL_DETAIL: 'af_screen_call_detail',
    ALL_MEETING_ROOM: 'af_screen_list_meeting',
    CREATE_ROOM: 'af_screen_create_room_meeting',
    EDIT_ROOM: 'af_screen_intro',
    DETAIL_MEETING_ROOM: 'af_screen_detail_meeting',
    DATE_PICKER_SCREEN: 'af_screen_date_picker',
    LIVE_STREAM: 'af_screen_live_stream',
    AUDIO_LIVE: 'af_screen_audio_live',
    MOM_PREP_TEST: 'af_screen_mom_prep_test',
    TEST_DETAIL: 'af_screen_test_detail',
    TEST_RESULT: 'af_screen_test_result',
    LIST_RECORD: 'af_screen_list_record',
    MASTER_CLASS: 'af_screen_master_class_detail',
    LIST_MASTER_CLASS: 'af_screen_list_master_class',
  },
  FORUM: {
    LIKE: 'post_liked',
    COMMENT: 'post_commented',
    CREATE_NEW_POST_BUTTON: 'post_create_new_post_button',
    REPLY: 'post_reply',
    CREATE_NEW_POST_PAGE: 'post_create_new_post_page',
    POST_IN_FORUM: 'post_in_forum',
  },
  TIDA: {
    TIDA_OPEN: 'tida_open',
    TIDA_ASK: 'tida_ask_questions',
  },
  BABY_TRACKER: {
    BABY_TRACKER_OPEN: 'baby_tracker_open',
    BABY_TRACKER_FORUM_SECTION: 'baby_tracker_forum_section',
    BABY_TRACKER_CHANGE_WEEK: 'baby_tracker_change_week',
    DAILY_QUIZ: 'daily_quiz',
    PODCAST_SCROLL: 'podcast_scroll',
    VIDEO_SCROLL: 'video_scroll',
    ARTICLE_SCROLL: 'article_scroll',
  },
  MOM_TEST: {
    START: 'MOM_TEST_START',
    DO: 'MOM_DO_DAILY_QUIZ',
  },
};
