export const typeListChat = {
  UPLOAD_LIST_CHAT: 'UPLOAD_LIST_CHAT',
  CREATE_LIST_CHAT: 'CREATE_LIST_CHAT',
  SEEN_CHAT: 'SEEN_CHAT',
  GET_LIST_USER_CHAT: 'GET_LIST_USER_CHAT',
  GET_SEARCH: 'GET_SEARCH',
  CHANGE_OPTION: 'CHANGE_OPTION',
  CLEAR_LIST_CHAT: 'CLEAR_LIST_CHAT',
};
