export enum Trimester {
    FIRST = 1,
    SECOND = 2,
    THIRD = 3,
}

export enum Mood {
    CALM = 'CALM',
    NERVOUS = 'NERVOUS',
    GRATEFUL = 'GRATEFUL',
    SAD = 'SAD'
}

export enum Topics {
    PREGNANCY_DEVELOPMENT = 'PREGNANCY_DEVELOPMENT',
    LABOUR = 'LABOUR',
    MEDICAL = 'MEDICAL',
    NUTRITION = 'NUTRITION',
    BABY_CARE = 'BABY_CARE',
    FITNESS_AND_WELLNESS = 'FITNESS_AND_WELLNESS',
    LIFE_AND_CAREER = 'LIFE_AND_CAREER',
    MENTAL_HEALTH = 'MENTAL_HEALTH'
}