const typeAuth = {
  LOGIN: 'LOGIN',
  SAVE_LANG: 'SAVE_LANG',
  SAVE_LOGIN_INFO: 'SAVE_LOGIN_INFO',
  CHANGE_STATUS_LOGIN: 'CHANGE_STATUS_LOGIN',
  LOG_OUT: 'LOG_OUT',
  SAVE_USER_INFO: 'SAVE_USER_INFO',
  SAVE_DATA_LOGIN_FACEBOOK: 'SAVE_DATA_LOGIN_FACEBOOK',
  CHANGE_WEEK: 'CHANGE_WEEK',
  IS_DONE_DAILY: 'IS_DONE_DAILY',
  IS_SEEN_COMMENT: 'IS_SEEN_COMMENT',
};

export {typeAuth};
