export const typeLiveTalk = {
  GET_DETAIL_ROOM_MEETING: 'GET_DETAIL_ROOM_MEETING',
  GET_DETAIL_ROOM_MEETING_SUCCESS: 'GET_DETAIL_ROOM_MEETING_SUCCESS',

  GET_DETAIL_INROOM_MEETTING: 'GET_DETAIL_INROOM_MEETTING',
  GET_DETAIL_INROOM_MEETTING_SUCCESS: 'GET_DETAIL_INROOM_MEETTING_SUCCESS',

  LEAVE_ROOM_MEETING: 'LEAVE_ROOM_MEETING',
  SHOW_MODAL_REVIEW: 'SHOW_MODAL_REVIEW',
  CLEAR_DATA_LIVETALK: 'CLEAR_DATA_LIVETALK',
};
