const typeHome = {
  GET_DATA_HOME: 'GET_DATA_HOME',
  GET_DATA_HOME_BY_WEEK: 'GET_DATA_HOME_BY_WEEK',
  GET_DATA_HOME_SUCCESS: 'GET_DATA_HOME_SUCCESS',
  UPDATE_DATA_HOME: 'UPDATE_DATA_HOME',
  CHANGE_WEEK_PREGNANT: 'CHANGE_WEEK_PREGNANT',
  CHANGE_WEEK: 'CHANGE_WEEK',
  LOADING_DONE: 'LOADING_DONE',
  PAY_VIDEO: 'PAY_VIDEO',
  PAY_ARTICLE: 'PAY_ARTICLE',
  PAY_PODCAST: 'PAY_PODCAST',
  PAY_MASTER_CLASS: 'PAY_MASTER_CLASS',
};

export {typeHome};
